/* eslint-disable */

// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// Application Redux Store reducer.  WARNING! This is autogenerated file! Do not edit it manually!
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

import { combineReducers } from 'redux';

import type { State } from './types';
import chart from './chart';

export default combineReducers<State>({
  chart,
});
